<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Capturing a screenshot]]>
    </line>
    <line>
      <![CDATA[<a target='_blank' href='C:/Users/Beni/Downloads/1676889880009.jpg'>Screenshot</a>]]>
    </line>
  </reporter-output>
  <suite started-at="2024-03-01T19:02:48 EET" name="Data Driven Basics" finished-at="2024-03-01T19:02:50 EET" duration-ms="1473">
    <groups>
    </groups>
    <test started-at="2024-03-01T19:02:48 EET" name="Manager Login Test" finished-at="2024-03-01T19:02:49 EET" duration-ms="775">
      <class name="testcases.BankManagerLoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:testcases.BankManagerLoginTest@58c34bb3]" started-at="2024-03-01T19:02:48 EET" name="loginAsBankManager" finished-at="2024-03-01T19:02:49 EET" duration-ms="748" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[test the listeners]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: test the listeners
at org.testng.Assert.fail(Assert.java:111)
at testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing a screenshot]]>
            </line>
            <line>
              <![CDATA[<a target='_blank' href='C:/Users/Beni/Downloads/1676889880009.jpg'>Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- testcases.BankManagerLoginTest -->
    </test> <!-- Manager Login Test -->
    <test started-at="2024-03-01T19:02:49 EET" name="Add Customer Test" finished-at="2024-03-01T19:02:50 EET" duration-ms="668">
      <class name="testcases.AddCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.AddCustomerTest@ed3068a]" started-at="2024-03-01T19:02:45 EET" name="setUp" finished-at="2024-03-01T19:02:48 EET" duration-ms="2942" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomer(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.AddCustomerTest@ed3068a]" started-at="2024-03-01T19:02:49 EET" name="addCustomer" data-provider="getData" finished-at="2024-03-01T19:02:50 EET" duration-ms="644" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[RandName]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[RandLast]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[23246.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="testDown()[pri:0, instance:testcases.AddCustomerTest@ed3068a]" started-at="2024-03-01T19:02:50 EET" name="testDown" finished-at="2024-03-01T19:02:50 EET" duration-ms="183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDown -->
      </class> <!-- testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
